// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using vetiflow.Server.Data;

#nullable disable

namespace vetiflow.Server.Migrations
{
    [DbContext(typeof(VetiFlowDbContext))]
    partial class VetiFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("vetiflow.Server.Models.AiSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmergencyCaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmergencyCaseId");

                    b.ToTable("AiSummaries");
                });

            modelBuilder.Entity("vetiflow.Server.Models.CaseEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EmergencyCaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmergencyCaseId");

                    b.ToTable("CaseEvents");
                });

            modelBuilder.Entity("vetiflow.Server.Models.EmergencyCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Acuity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedDoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedTechnicianId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DischargedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NextAction")
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("PresentingComplaint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("EmergencyCases");
                });

            modelBuilder.Entity("vetiflow.Server.Models.Handoff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmergencyCaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FromStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("NextSteps")
                        .HasColumnType("text");

                    b.Property<string>("PendingItems")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ToStaffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmergencyCaseId");

                    b.ToTable("Handoffs");
                });

            modelBuilder.Entity("vetiflow.Server.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Breed")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("vetiflow.Server.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("vetiflow.Server.Models.StaffMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("vetiflow.Server.Models.TriageAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Acuity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AssessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssessedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("CapillaryRefillTime")
                        .HasColumnType("text");

                    b.Property<Guid>("EmergencyCaseId")
                        .HasColumnType("uuid");

                    b.Property<int?>("HeartRate")
                        .HasColumnType("integer");

                    b.Property<string>("Mentation")
                        .HasColumnType("text");

                    b.Property<string>("MucousMembraneColor")
                        .HasColumnType("text");

                    b.Property<string>("RawIntakeNotes")
                        .HasColumnType("text");

                    b.Property<int?>("RespiratoryRate")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TemperatureF")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("EmergencyCaseId");

                    b.ToTable("TriageAssessments");
                });

            modelBuilder.Entity("vetiflow.Server.Models.AiSummary", b =>
                {
                    b.HasOne("vetiflow.Server.Models.EmergencyCase", "EmergencyCase")
                        .WithMany()
                        .HasForeignKey("EmergencyCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmergencyCase");
                });

            modelBuilder.Entity("vetiflow.Server.Models.CaseEvent", b =>
                {
                    b.HasOne("vetiflow.Server.Models.EmergencyCase", "EmergencyCase")
                        .WithMany()
                        .HasForeignKey("EmergencyCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmergencyCase");
                });

            modelBuilder.Entity("vetiflow.Server.Models.EmergencyCase", b =>
                {
                    b.HasOne("vetiflow.Server.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("vetiflow.Server.Models.Handoff", b =>
                {
                    b.HasOne("vetiflow.Server.Models.EmergencyCase", "EmergencyCase")
                        .WithMany()
                        .HasForeignKey("EmergencyCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmergencyCase");
                });

            modelBuilder.Entity("vetiflow.Server.Models.TriageAssessment", b =>
                {
                    b.HasOne("vetiflow.Server.Models.EmergencyCase", "EmergencyCase")
                        .WithMany()
                        .HasForeignKey("EmergencyCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmergencyCase");
                });
#pragma warning restore 612, 618
        }
    }
}
